---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:

- name: Install Appache httpd (state=present is optional)
apt:
  name: apache2
  state: absent
  #port 80 is in so leave absent
